name: habitracker
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  build_runner: ^2.4.9
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_iconpicker: ^3.4.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  percent_indicator: ^4.2.3
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
